[package]
name = "zt-sys"
version = "1.8.6"
edition = "2021"
build = "build.rs"

[lib]
name = "zt_sys"
path = "src/lib.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
bindgen = "0.59"

